### ISSUE TITLE
Question: How to use evalContext in contrib test page.

### ISSUE THREAD

**Issue by Brokkoly** [formio/contrib#16]
I use contrib's test page quite a bit for custom component development, but I also heavily use the evalContext for my validators. Is there a good way to inject the evalContext into the form for doing this testing? My assumption would be in https://github.com/formio/contrib/blob/master/index.html. Thank You

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
