### ISSUE TITLE
Error with IE11 [BUG] 

### ISSUE THREAD

**Issue by mrcandu** [formio/contrib#4]
## Environment

Windows
NodeJS 10.15.1

## Issue

I have an issue building this template to support ie11.
When including the `formio-contrib.use.min.js` file along with formiojs, I am seeing an error triggered on the `formio.full.min.js` file in IE11:
`e.fetch.polyfill=!0`

Chrome and Edge work as expected.

The original bundled  `contrib/dist/formio-contrib.use.min.js` works fine , so it seems to be an issue with the build?
Typescript seems to be configured for IE11 support. I have tried different versions of Node and dependencies, but no luck so far.

## To reproduce

Download the repo
run `npm install` and use the newly built `formio-contrib.use.min.js` file as described in the readme:

```
Or you can use the formio-contrib.use.min.js file which automatically adds the Formio.use method.

<link rel="stylesheet" href="https://unpkg.com/formiojs@latest/dist/formio.full.min.css">
<script src="https://unpkg.com/formiojs@latest/dist/formio.full.min.js"></script>
<script src="https://unpkg.com/@formio/contrib@latest/dist/formio-contrib.use.min.js"></script>
<link rel="stylesheet" href="https://unpkg.com/@formio/contrib@latest/dist/formio-contrib.css">
```

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
